//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Olá {0}!&lt;/div&gt;
        ///           &lt;div&gt;Aqui está seu código de validação:&lt;/div&gt;
        ///		   &lt;/br&gt;
        ///           &lt;div&gt;&lt;b&gt;{1}&lt;/b&gt;&lt;/div&gt;
        ///		   &lt;/br&gt;
        ///	       &lt;div&gt;Em caso de dúvidas entre em contato com administrador do sistema.&lt;/div&gt;
        ///		   &lt;/br&gt;
        ///	       &lt;div&gt;Atenção: esta mensagem de e-mail foi enviada de um endereço de notificação. Por favor, não responda este e-mail.&lt;/div&gt;.
        /// </summary>
        internal static string bodyEmailCode {
            get {
                return ResourceManager.GetString("bodyEmailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Olá {0}!&lt;/div&gt;
        ///           &lt;div&gt;Aqui está o link para redefinição de senha:&lt;/div&gt;
        ///		   &lt;/br&gt;
        ///           &lt;div&gt;&lt;b&gt;{1}&lt;/b&gt;&lt;/div&gt;
        ///		   &lt;/br&gt;
        ///	       &lt;div&gt;Em caso de dúvidas entre em contato com administrador do sistema.&lt;/div&gt;
        ///		   &lt;/br&gt;
        ///	       &lt;div&gt;Atenção: esta mensagem de e-mail foi enviada de um endereço de notificação. Por favor, não responda este e-mail.&lt;/div&gt;.
        /// </summary>
        internal static string bodyEmailResetPassword {
            get {
                return ResourceManager.GetString("bodyEmailResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Academy- Verificação de E-mail.
        /// </summary>
        internal static string SubjectEmail {
            get {
                return ResourceManager.GetString("SubjectEmail", resourceCulture);
            }
        }
    }
}
